export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const SAVE_PLACE = 'SAVE_PLACE';
export const UPDATE_PLACES = 'UPDATE_PLACES';
export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const SAVE_WITHIN_MODAL = 'SAVE_WITHIN_MODAL';
export const CURRENT_NOTE_TEXT = 'CURRENT_NOTE_TEXT';
